"""Add Comments column(disabled)

Revision ID: 28e7fb0365d6
Revises: 3eaf51b2047b
Create Date: 2019-03-16 15:57:03.796515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28e7fb0365d6'
down_revision = '3eaf51b2047b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('disabled', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_comment_timestamp'), 'comment', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comment_timestamp'), table_name='comment')
    op.drop_column('comment', 'disabled')
    # ### end Alembic commands ###
