"""Add Post.body_html column for supporting makrdown

Revision ID: e0e02ee979c9
Revises: 9d0f55c2725d
Create Date: 2019-03-12 11:29:26.710100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0e02ee979c9'
down_revision = '9d0f55c2725d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    # ### end Alembic commands ###
